### ISSUE TITLE
Unable to resolve CoverageEntity in applied gradle file

### ISSUE THREAD

**Issue by wesley-crick** [gw-kit/delta-coverage-plugin#144]
**Describe the bug**
When trying to access a `CoverageEntity` outside of a parent level `build.gradle` file, it fails to resolve during a gradle sync.

**Desktop (please complete the following information):**
 - OS: Mac 14.4.1 (23E224)
 - Gradle version: 8.9
 - Delta Coverage plugin version: 2.5.0

**To Reproduce**
build.gradle
```groovy
...
apply from: rootProject.file('./gradle/delta-coverage.gradle')
...
```
delta-coverage.gradle
```groovy
import io.github.surpsg.deltacoverage.gradle.CoverageEntity
deltaCoverageReport {
    violationRules {
        rule(CoverageEntity.INSTRUCTION) {
            minCoverageRatio.set(0.9d)
        }
    }
...
}
```

**Expected behavior**
Allow for applied gradle files to access the `CoverageEntity` enum.

**Logs**
```
FAILURE: Build failed with an exception.

* Where:
Script '/Users/username/Documents/android-app/gradle/delta-coverage.gradle' line: 1

* What went wrong:
Could not compile script '/Users/username/Documents/android-app/gradle/delta-coverage.gradle'.
> startup failed:
  script '/Users/username/Documents/android-app/gradle/delta-coverage.gradle': 1: unable to resolve class io.github.surpsg.deltacoverage.gradle.CoverageEntity
   @ line 1, column 1.
     import io.github.surpsg.deltacoverage.gradle.CoverageEntity
     ^
  
  1 error
```

**Additional context**
The import works fine from the project/module level `build.gradle`, but as soon as it is moved into a separate gradle file, it fails to find the import.

**Comment by SurpSG** [comment]
Hi @wesley-crick 

Please try 
```groovy

deltaCoverageReport {
    violationRules {
        rule('INSTRUCTION') {
            minCoverageRatio.set(0.9d)
        }
    }
}

```

**Comment by wesley-crick** [comment]
Haha yup that works. Thanks a lot! 🙏
